/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_codebrothers_jpio_JPIO */

#ifndef _Included_org_codebrothers_jpio_JPIO
#define _Included_org_codebrothers_jpio_JPIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_codebrothers_jpio_JPIO
 * Method:    initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_codebrothers_jpio_JPIO_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_codebrothers_jpio_JPIO
 * Method:    getGPIO
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_codebrothers_jpio_JPIO_getGPIO
  (JNIEnv *, jclass);

/*
 * Class:     org_codebrothers_jpio_JPIO
 * Method:    getClock
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_codebrothers_jpio_JPIO_getClock
  (JNIEnv *, jclass);

/*
 * Class:     org_codebrothers_jpio_JPIO
 * Method:    getPWM
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_codebrothers_jpio_JPIO_getPWM
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
