/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdint.h>

#ifndef _Included_org_codebrothers_jpio_JPIO
#define _Included_org_codebrothers_jpio_JPIO
#ifdef __cplusplus
extern "C" {
#endif

#define PERI_BASE               0x20000000
#define GPIO_BASE               (PERI_BASE + 0x200000)

/// Size of memory page on RPi
#define PAGE_SIZE               (4*1024)

/// Size of memory block on RPi
#define BLOCK_SIZE              (4*1024)

/*
 * Class:     org_codebrothers_jpio_JPIO
 * Method:    mapGPIO
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_codebrothers_jpio_JPIO_mapGPIO
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
